In [12]:
import numpy as np

In [20]:
mylist = [1,2,3,4]

In [22]:
myarr = np.array(mylist)

In [26]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [40]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [42]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [50]:
np.random.rand(2,5)

array([[0.46396891, 0.36186943, 0.74631948, 0.64315433, 0.37642554],
       [0.46689421, 0.3755062 , 0.29938237, 0.88241715, 0.87569355]])

In [54]:
np.random.randn(3,5)

array([[-0.54531435,  0.11627668, -1.10667023,  1.45723967, -0.9795499 ],
       [ 0.13376715,  0.54527633,  0.07265256,  0.58229037, -0.6202825 ],
       [ 0.33141334,  0.37574043,  1.27389079,  0.60261795,  0.75477019]])

In [62]:
np.random.randint(3,101,(4,6))

array([[67, 51, 52, 43, 93, 16],
       [97, 68, 10, 37, 52, 86],
       [ 3, 24, 76, 20, 47, 83],
       [17, 11, 62,  9, 45, 55]])

In [64]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [138]:
arr = np.arange(0,25)

In [76]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [78]:
ranarr = np.random.randint(0,101,10)

In [80]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [82]:
ranarr.max()

99

In [84]:
ranarr.min()

2

In [86]:
ranarr.argmax()

5

In [88]:
ranarr.argmin()

7

In [90]:
ranarr.dtype

dtype('int32')

In [140]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [94]:
arr.shape

(25,)

In [146]:
arr = arr.reshape(5,5)

In [148]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
arr.shape

(5, 5)

In [152]:
#indixing the row and column using arr
arr[:2,0:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [154]:
arr [0:2,3] = 100

In [156]:
arr

array([[  0,   1,   2, 100,   4],
       [  5,   6,   7, 100,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [158]:
arr_copy = arr.copy()

In [162]:
arr_copy[:] = 2

In [164]:
arr_copy

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [166]:
arr

array([[  0,   1,   2, 100,   4],
       [  5,   6,   7, 100,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [168]:
arr > 4

array([[False, False, False,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [170]:
bool_rr = arr <12

In [172]:
bool_rr

array([[ True,  True,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [176]:
arr[bool_rr]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10, 11])

In [178]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


In [180]:
dice_rolls > 2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [184]:
dice_rolls[dice_rolls > 2].shape

(19,)

In [188]:
np.log(arr)

C:\Users\demon\AppData\Local\Temp\ipykernel_20896\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[      -inf, 0.        , 0.69314718, 4.60517019, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 4.60517019, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383]])

In [190]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743, -0.50636564, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 , -0.50636564,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [192]:
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356, 10.        ,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131, 10.        ,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
       [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949]])

In [194]:
arr.std()

24.70802298849505

In [208]:
arr2d = np.arange(0,25).reshape(5,5)

In [210]:
arr2d.shape

(5, 5)

In [212]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [214]:
arr2d.sum()

300

In [216]:
arr2d.sum(axis = 0)#across the columns 

array([50, 55, 60, 65, 70])

In [218]:
arr2d.sum(axis = 1 )#across the rows

array([ 10,  35,  60,  85, 110])

In [222]:
arr2d.max(axis = 0)#across the columns  

array([20, 21, 22, 23, 24])

#A bank account has had withdrawals and deposits tracked in a numpy array called account_transactions. Based on this list of account transactions, what is the total remaining in the account? Assign your answer to a variable called account_total.account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [245]:
account_transactions= np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [251]:
account_total = account_transactions.sum()

In [253]:
account_total

2720

In [265]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])